# Gets to -0.576 rew after 1.6 million
seeker-ppo:
    env: MultiRobot-v0
    run: PPO
    checkpoint_freq: 10
    stop:
        episode_reward_mean: 6000
    config:
        gamma: 0.995
        lambda: 0.95
        clip_param: 0.2
        kl_coeff: 1.0
        num_sgd_iter: 20
        lr: .0001
        sgd_minibatch_size: 3276
        horizon: 90
        train_batch_size: 32000
        model:
            free_log_std: true
        num_workers: 2
        num_gpus: 0
        batch_mode: complete_episodes